paths:
  dir: "C:/Users/blongacr/OneDrive - Russel Metals/Documents/Projects/Cyber Security/Crowdstrike/Source Data"
  outdir: "C:/Users/blongacr/OneDrive - Russel Metals/Documents/Projects/Cyber Security/Crowdstrike/Viz/output"

pattern: "Daily Vulnerability Export - ALL - *combined - prepped.csv"
theme: plotly_dark
sep: "\t"
encoding: "utf-8"

status_mode: open
topk: 10
show_values: true

# pick one of these; CLI overrides both
window_weeks: 13
# window_days: 90